name: Docker CI - Build & Push to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: dockerized-webapp

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::521145340284:role/GitHubActions-OIDC-Role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          521145340284.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          521145340284.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push Docker image to ECR
        run: |
          docker push 521145340284.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
          docker push 521145340284.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Deploy via AWS SSM
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=i-087ab6e86a55bc06f" \
          --comment "Deploy Dockerized Web App" \
          --parameters commands="[
          \"docker pull 521145340284.dkr.ecr.us-east-1.amazonaws.com/dockerized-webapp:latest\",
          \"docker stop dockerized-webapp || true\",
          \"docker rm dockerized-webapp || true\",
          \"docker run -d --name dockerized-webapp -p 8080:8080 521145340284.dkr.ecr.us-east-1.amazonaws.com/dockerized-webapp:latest\"
          ]" \
          --region us-east-1



#test